kernel.randomize_va_space = 0
kernel.sched_rr_timeslice_ms = 50
vm.compaction_proactiveness = 0
vm.dirty_background_ratio = 20
vm.dirty_expire_centisecs = 6000
vm.dirty_ratio = 20
vm.dirty_writeback_centisecs = 6000
vm.enable_soft_offline = 0
vm.extfrag_threshold = 100
vm.laptop_mode = 0
vm.oom_dump_tasks = 0
vm.oom_kill_allocating_task = 1
vm.stat_interval = 30
vm.swappiness = 0
vm.vfs_cache_pressure = 20
